const int MAX_SCISSORHEIGHT = 2000; // This is maximum change in potentiometer value
const int MIN_SCISSORHEIGHT = 0;
const int MAX_FOURBARHEIGHT = 4000;
const int MIN_FOURBARHEIGHT = 0;
const int MIN_MOGO = 2337;
const int MAX_MOGO = 4050;
const float SLEW_OFFSET = .8;
const int MAXPOWER = 90;
const int TURN_MAXPOWER = 127;
const float P_FACTOR = 20;
const int WAIT_FOR_STOP = 200;
const int TURN_90 = 575;
const int TURN_180 = 1475;
int Scissortarget = 0;
int FourBarTarget = 0;
int MogoTarget = MAX_MOGO;
bool ScissorLiftControl = false;
bool FourControl = false;
bool MobileGoal = false;
