const int MAX_SCISSORHEIGHT = 2000; // This is maximum change in potentiometer value
const int MIN_SCISSORHEIGHT = 0;
const int MAX_FOURBARHEIGHT = 2800; // Up
const int MIN_FOURBARHEIGHT = 950; // Down
const int MIN_MOGO = 1150; // Out
const int MAX_MOGO = 2000; // In
const float SLEW_OFFSET = .8;
const int MAXPOWER = 127;
const int TURN_MAXPOWER = 127;
const float P_FACTOR = 20;
const int WAIT_FOR_STOP = 200;
const int TURN_90 = 575;
const int TURN_180 = 1475;
const int SCISSOR_DOWN_POWER=100;
int Scissortarget = 0;
int FourBarTarget = 0;
const int FOUR_BAR_STRAIGHT = 1700;
const int MIN_FOUR_BAR_MOGO = 1300;
int MogoTarget = MAX_MOGO;
bool ScissorLiftControl = false;
bool FourControl = false;
bool MobileGoal = false;
