#pragma config(Sensor, in1,    MogoSensor,     sensorPotentiometer)
#pragma config(Motor,  port2,           RightFrontFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightFrontBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RightBackFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightBackBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LeftFrontFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftFrontBack, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LeftBack,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Mogo,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "slew motor program.c"
bool tankControl=true;
int RightDrive = 0;
int LeftDrive = 0;
const int MIN_MOGO = 1491;
const int MAX_MOGO = 2540;
int MogoTarget = MAX_MOGO;
bool MobileGoal = false;
#define DEADBAND 20

int min(int a, int b) {
	if (a > b)
		return b;
	return a;
}

int max(int a, int b) {
	if (a > b)
		return a;
	return b;
}
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task MobileGoalControl()
{
	int MogoTarget = 0;
	int MogoError = 0;
	int MogoSpeed = 0;
	while(true)
	{
		if(MobileGoal)
		{
			if (MogoTarget > MAX_MOGO)
			{
				MogoTarget = MAX_MOGO;
			}
			if (MogoTarget < MIN_MOGO)
			{
				MogoTarget = MIN_MOGO;
			}
			// Defining Our Current value
			int CurrentMogoValue = SensorValue[MogoSensor];
			// Defining Error
			MogoError = MogoTarget - CurrentMogoValue;
			if (abs(MogoError) < 50)
				MogoError = 0;
			//setting Mogo Speed
			MogoSpeed = MogoError/2;

			if (MogoSpeed > 127)
			{
				MogoSpeed = 127;
			}
			else if (MogoSpeed < -127)
			{
				MogoSpeed = -127;
			}
			else if (abs(MogoSpeed) < 25)
			{
				MogoSpeed = 0;
			}
		}
		motorReq[Mogo] = -MogoSpeed;
		wait1Msec(MOTOR_TASK_DELAY);
	}
}
task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
//	startTask(MobileGoalControl);
//	startTask(MotorSlewRateTask);
	MobileGoal = true;
	float SLOW_DOWN = .8;
	while(true)
	{


		if (vexRT[Btn6U] == 1) tankControl=true;
		if (vexRT[Btn6D] == 1) tankControl=false;

		RightDrive = 0;
		LeftDrive = 0;

		if (tankControl) {
			if(abs(vexRT[Ch2])>DEADBAND)
			{
				RightDrive = vexRT[Ch2] * SLOW_DOWN;
			}
			if (abs(vexRT[Ch3])>DEADBAND)
			{
				LeftDrive = vexRT[Ch3] * SLOW_DOWN;
			}
			} else {
			if(abs(vexRT[Ch2])>DEADBAND)
			{
				RightDrive = vexRT[Ch2] * SLOW_DOWN;
				LeftDrive = vexRT[Ch2] * SLOW_DOWN;
			}
			if (abs(vexRT[Ch4])>DEADBAND)
			{
				LeftDrive = vexRT[Ch4]/2;
				RightDrive = -vexRT[Ch4]/2;
			}
		}

		if(vexRT[Btn5U] == 1)
		{
			Mogotarget = min(MAX_MOGO, Mogotarget + 30); //Decreased from 30 to 1, the loop is execute many times per seconds, so the value was changing too fast
			MobileGoal = true;
		}
		else if(vexRT[Btn5D] == 1)
		{
			MogoTarget = Max(MIN_MOGO, MogoTarget - 30);
			MobileGoal = true;
		}
		if(vexRT[Btn8U] == 1)
		{
			SLOW_DOWN = 1;
		}
		if(vexRT[Btn8D] == 1)
		{
			SLOW_DOWN = .8;
		}
	/*	if(vexRT[Btn7U] == 1)
		{
			motor[B
		}*/
		motor[RightFrontFront] = RightDrive;
		motor[RightFrontBack] = RightDrive;
		motor[RightBackBack] = RightDrive;
		motor[RightBackFront] = RightDrive;
		motor[LeftFrontFront] = LeftDrive;
		motor[LeftFrontBack] = LeftDrive;
		motor[LeftBack] = LeftDrive;
	}

}
