#pragma config(Motor,  port2,           RightFrontFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RightFrontBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RightBackFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightBackBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LeftFrontFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LeftFrontBack, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LeftBack,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Mogo,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{




}
